---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: dot-net-test
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: jfrog.kemo.labs/docker-remote/bencuk/dotnet-demoapp:latest
          #image: docker.io/bencuk/dotnet-demoapp
          #image: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-212.1679308152
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 150m
              memory: 100Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: httpd-test
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: custom-page
          configMap:
            name: custom-page
      containers:
        - name: httpd
          image: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-212.1679308152
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 150Mi
            requests:
              cpu: 150m
              memory: 100Mi
          volumeMounts:
            - name: custom-page
              mountPath: /var/www/html/