---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: dot-net-test
spec:
  selector:
    app: dotnet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: httpd-test
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080